# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Dream Plus Light"
license = "MIT"
licenselink = "https://github.com/UtkarshVerma/hugo-dream-plus/blob/master/LICENSE"
description = "Build on dream plus to pass lighthouse test with 100 performance."
homepage = "https://blog.atlantishq.de/"
tags = ["clean", "blog", "responsive","personal","single page","material design"]
features = ["randomBackground","favicon","blurBackground","home cards","flip", "colorful", "imagebackground", "i18n", "copyright", "motto"]
min_version = "0.38"

[author]
	name = "Sheppy"
	homepage = "https://blog.atlantishq.de"

# If porting an existing theme
[original]
	name = "UtkarshVerma's Blog"
	homepage = "https://utkarshverma.github.io"
	repo = "https://github.com/UtkarshVerma/utkarshverma.github.io"
